### ISSUE TITLE
Dev / find a QR Code library/API

### ISSUE THREAD

**Issue by JTLee98** [CMPUT301W22T33/QR-Code-Pursuit#33]
find something to handle QR code scanning / recognition

**Comment by JTLee98** [comment]
since kev @crunchycakes is working on the QR scanning / image / camera stuff might as well assign this one to you bud, hope you dont mind

**Comment by crunchycakes** [comment]
found the following resources under the same repo
https://github.com/yuriy-budiyev/code-scanner
https://github.com/kenglxn/QRGen
